"Run3Summer22NanoAODv11-126X":
    "names":
        - /DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv11-126X_mcRun3_2022_realistic_v2-v1/NANOAODSIM
        - /WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv11-126X_mcRun3_2022_realistic_v2-v1/NANOAODSIM
    "gjson":
        dummy
    "type":
        mc

"2022C":
    "names":
        - /Muon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
        - /SingleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
    "gjson":
        configs/jsons/Cert_Collisions2022_eraC_355862_357482_Golden.json
    "type":
        data

"2022D":
    "names":
        - /Muon/Run2022D-PromptNanoAODv10_v2-v1/NANOAOD
    "gjson":
        configs/jsons/Cert_Collisions2022_eraD_357538_357900_Golden.json
    "type":
        data
        
"2022E":
    "names":
        - /Muon/Run2022E-PromptNanoAODv10_v1-v3/NANOAOD
    "gjson":
        configs/jsons/Cert_Collisions2022_eraE_359022_360331_Golden.json
    "type":
        data
        
"2022F":
    "names":
        - /Muon/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
    "gjson":
        configs/jsons/Cert_Collisions2022_eraF_360390_362167_Golden.json
    "type":
        data
        
"2022G":
    "names":
        - /Muon/Run2022G-PromptNanoAODv11_v1-v2/NANOAOD
    "gjson":
        configs/jsons/Cert_Collisions2022_eraG_362433_362760_Golden.json
    "type":
        data
        

