"2022":
  "mc":
    "Run3Summer22NanoAODv11-126X":
      "samples":
        - /DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv11-126X_mcRun3_2022_realistic_v2-v1/NANOAODSIM
        - /WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv11-126X_mcRun3_2022_realistic_v2-v1/NANOAODSIM
     
  "data":
    "2022B":
      "samples":
        - /SingleMuon/Run2022B-22Sep2023-v1/NANOAOD
      "gjson":
        configs/jsons/Cert_Collisions2022_eraB_355100_355769_Golden.json
    "2022C":
      "samples":
        - /Muon/Run2022C-22Sep2023-v1/NANOAOD
      "gjson":
        configs/jsons/Cert_Collisions2022_eraC_355862_357482_Golden.json
    "2022D":
      "samples":
        - /Muon/Run2022D-22Sep2023-v1/NANOAOD
      "gjson":
        configs/jsons/Cert_Collisions2022_eraD_357538_357900_Golden.json
    "2022E":
      "samples":
        - /Muon/Run2022E-22Sep2023-v1/NANOAOD
      "gjson":
        configs/jsons/Cert_Collisions2022_eraE_359022_360331_Golden.json
    "2022F":
      "samples":
        - /Muon/Run2022F-PromptNanoAODv10_v1-v2/NANOAOD
      "gjson":
        configs/jsons/Cert_Collisions2022_eraF_360390_362167_Golden.json
    "2022G":
      "samples":
        - /Muon/Run2022G-PromptNanoAODv11_v1-v2/NANOAOD
      "gjson":
        configs/jsons/Cert_Collisions2022_eraG_362433_362760_Golden.json
